palomachain/paloma

.air.toml, Dockerfile
- https://github.com/palomachain/paloma/issues/85
Making it easier to work locally. This will trigger a live reload of code.
=> Live reload

Dockerfile, scripts/setup-chain-validator.sh
- #85 
This PR enables us to run paloma chain in docker locally and build the chain using the right config
=> Local setup for docker

.github/workflows/release.yml, .gitignore, .goreleaser.yaml, Dockerfile
- #129 
Does a release for the chain
=> Go releaser

README.md, scripts/setup-chain-validator.sh
https://github.com/palomachain/paloma/issues/139
We need instructions for setting up a new chain, both from scratch and connecting to an existing one.
=> Add instructions for setting up a new chain.

.github/ISSUE_TEMPLATE/frontend-request.md
Adding a template that the whole org can use when FE and/or Design work is needed.
=> Add Frontend request to issue templates

docs/static/openapi.yml, proto/consensus/tx.proto, x/consensus/client/cli/tx.go, x/consensus/client/cli/tx_delete_job.go, x/consensus/handler.go, x/consensus/keeper/concensus_keeper.go, x/consensus/keeper/msg_server_delete_job.go, x/consensus/module_simulation.go, x/consensus/simulation/delete_job.go, x/consensus/types/codec.go, x/consensus/types/message_delete_job.go, x/consensus/types/tx.pb.go, x/evm/types/abi.go
- #168 
Delete job from queue and correctly hash the bytes for the EVM
=> Delete job from queue and correctly hash the bytes for the EVM

README.md
https://github.com/palomachain/paloma/issues/143
Organize our testnet setup documentation better, explicitly add connection strings, and generally
address retrospective items from previous testnet deploy.
=> Testnet documentation update

README.md
https://github.com/palomachain/paloma/issues/143
Continue to evolve testnet creation instructions.
[Rendered.](https://github.com/palomachain/paloma/blob/chase-new-testnet/README.md)
=> Update testnet instructions with addrbook

README.md
[Passerina EPIC](https://www.notion.so/volumefi/EPIC-06-17-Paloma-Public-Testnest-1-d11ce23143c7475a9157acd224933d81)
Update instructions to initialize passerina testnet
=> Update instructions for passerina testnet

scripts/setup-volume-testnet.sh
[Public Testnet EPIC](https://www.notion.so/volumefi/EPIC-06-17-Paloma-Public-Testnest-1-d11ce23143c7475a9157acd224933d81)
We want a number of different values for testnet initialization, add them here.
=> Initialize new testnets with updated values

README.md, scripts/setup-volume-testnet.sh
https://github.com/palomachain/paloma/issues/247
We cannot keep reusing the same chain-id.
=> Choose a new chain-id when we make a new chain.

testutil/keeper/valset.go, util/slice/filter.go, x/consensus/keeper/consensus/consensus_test.go, x/consensus/keeper/consensus/mocks/Queuer.go, x/evm/keeper/keeper.go, x/evm/keeper/keeper_integration_test.go, x/evm/keeper/msg_server_submit_new_job.go, x/evm/types/turnstone_abi.go, x/valset/keeper/keeper.go, x/valset/keeper/setup_test.go
- https://github.com/palomachain/paloma/issues/243
Tests for the last week's effort.
=> Tests for compass communication

README.md
https://github.com/palomachain/paloma/issues/247
New testnet!
=> Update README for paloma-testnet-5

README.md
https://github.com/palomachain/paloma/issues/247
These should have been fixed with the main update.
=> s/grain/000000ugrain, remove last reference to paloma-testnet-4

scripts/setup-volume-testnet.sh
https://github.com/palomachain/paloma/issues/267
We want these values to be different.
=> Change seed values for initial validators for testnet

x/valset/keeper/keeper.go, x/valset/keeper/keeper_test.go, x/valset/module.go
- https://github.com/palomachain/paloma/issues/78
=> Optimize how often and when we create new snapshots

README.md
=> update version for upgrade section in README

.github/workflows/linter.yml
=> Use linter proposed by github

x/consensus/module.go, x/evm/keeper/attest.go, x/evm/keeper/keeper.go, x/evm/keeper/keeper_test.go
Yep.  I changed the way when context cache is saved. If there is an error, then it will save it now.
=> Tests for deploying a smart contract again

app/app_setup.go, x/consensus/keeper/concensus_keeper.go, x/consensus/keeper/msg_server_delete_job.go, x/evm/keeper/keeper.go, x/evm/keeper/keeper_test.go
We are missing few log lines around the code which makes it bit harder to debug. This also returns an error when it cannot deploy a new smart contract if there was no consensus.
Yes. Returning an error when smart contract cannot be deployed
=> Add log lines around EVM and consensus

x/valset/keeper/grpc_query_get_validator_jail_reason.go
- https://github.com/palomachain/paloma/issues/406
=> Not returning error when validator is not jailed

x/evm/keeper/keeper.go
=> Disable logic calls

x/evm/keeper/attest_validator_balance_test.go, x/evm/keeper/attest_validator_balances.go
- #430 
See title
A breaking change.
=> Do not jail a pigeon if their balance is equal to the min threshold balance

x/evm/keeper/keeper.go, x/valset/keeper/keeper.go, x/valset/keeper/keeper_test.go
- https://github.com/palomachain/paloma/issues/440
Just to give us more info why new snapshot was generated.
Nope. This is only adding log lines.
=> Logging why snapshot was generated

cmd/palomad/main.go
- #450 
The way that cobra-cmd works is that it will execute the nearest parent's persistent pre run command and it will not follow the callstack all the way to the root. Given that a new persistent prerun was added, it never executed the root's persistent prerun which was in charge of preparing the client which doesn't really feel natural :/
None.
=> Fix staking command

README.md
=> libwasmvm.x86_64.so path has changed at cosmwasm repo

README.md
README update for new Paloma release that Fixes #462 and #476
README update with correct release version numbers.
1. Verify the release numbers.
None
=> Readme update testnet 10 logic call upgrade

app/app.go
https://github.com/palomachain/paloma/issues/504
Yes, but in a positive way ;)
=> Register WASMD with snapshot manager

x/paloma/keeper/keeper.go, x/treasury/module.go
=> Possible non deterministic behaviour

.github/workflows/ci-test.yml, .github/workflows/codeql-analyzer.yml, app/pigeon.go, util/slice/go_map.go, x/consensus/client/cli/tx_add_messages_signatures.go, x/paloma/handler.go, x/treasury/handler.go
https://github.com/palomachain/paloma/issues/526
This analyzer may be a little noisy initially, but will hopefully tell us where new issues are creeping in. Going to silence the remainder of the warnings and merge it (for now).
=> Add codeql-analyzer to CI

app/app.go, x/consensus/keeper/concensus_keeper.go, x/consensus/keeper/consensus/batch.go, x/consensus/keeper/consensus/batch_test.go, x/consensus/keeper/consensus/consensus.go, x/consensus/keeper/consensus/consensus_test.go, x/consensus/keeper/consensus/mocks/Queuer.go, x/consensus/keeper/consensus/types.go, x/evm/keeper/errors.go, x/evm/keeper/keeper.go, x/evm/keeper/keeper_test.go, x/evm/types/expected_keepers.go, x/scheduler/keeper/keeper.go, x/scheduler/keeper/wasm_handler.go, x/scheduler/keeper/wasm_handler_test.go, x/scheduler/types/errors.go
Making it easier for clients (CosmWasm smart contract in this case) to call the paloma jobs.
Yep.
=> Execute jobs through CosmWasm

go.mod, go.sum
Fixes https://github.com/palomachain/paloma/issues/548
See https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.9
=> Use cosmos sdk version of ics

scripts/setup-volume-testnet.sh
Switching vera to the main validator, generating a new testnet/genesis.
=> Edits for paloma-testnet-13

util/slice/go_map.go, x/evm/keeper/attest.go
It's important on the critical path to iterate maps in order, this function will help accomplish that.
=> Fix FromMapKeys, resolve some go map iteration issues.

go.mod, go.sum
closes: #562
_Fix to IAVL issues that blocked upgrade after Dragonberry.
=> Update iavl_v0.19.3 to v0.19.4

README.md
N/A. Just update the readme for the latest tag.
Just update the readme for the latest tag for paloma.
1. Running in production
None.
=> Update README to the current palomad tag v0.11.4

x/evm/keeper/keeper.go
=> add logs for constructor parameters

.github/dependabot.yml, go.mod, go.sum
- Update go-ethereum
- Setup dependabot
closes: #597
=> chore: update deps

x/consensus/keeper/attest.go
Fixing #611 
Fixing the print statement for logging attest.go
None
None
=> add updates from #611 to fix consensus logs

x/consensus/keeper/concensus_keeper.go
=> revert logs

x/consensus/keeper/attest.go, x/evm/keeper/keeper.go
=> remove logs

.mergify.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, x/evm/keeper/attest.go, x/evm/keeper/attest_validator_balances.go, x/evm/keeper/keeper.go, x/valset/keeper/keeper.go
Adding logs
More Logging for paloma-testnet-14
Private testnet verified
None
=> Merge Additional Logs into new v0.11.6 release of Paloma.

README.md
See Changelog
Update README for new chain-id
N/A
N/A
=> Update README for paloma-testnet-14

.golangci.yml, Dockerfile, Makefile, scripts/golangci-lint.sh, third_party/.gitignore
No tickets. We want to improve the quality of our code, make it less error-prone.
We introduce static checks in the code (linting)
Only bumped Go version in Docker image (1.19->1.20), so no need to test.
No changes
=> Added rule in Makefile to locally lint the project + a script to set up linter (cross-platform)

go.mod, go.sum, internal/x-chain/types.go, util/keeper/errors.go, x/consensus/client/cli/query_queued_messages_for_signing.go, x/consensus/keeper/concensus_keeper.go, x/consensus/keeper/consensus/errors.go, x/consensus/keeper/errors.go, x/consensus/keeper/grpc_query_get_all_queue_names.go, x/evm/client/cli/tx_proposal.go, x/evm/genesis.go, x/evm/keeper/attest.go, x/evm/keeper/attest_test.go, x/evm/keeper/errors.go, x/evm/keeper/keeper.go, x/evm/keeper/keeper_test.go, x/evm/keeper/treasury.go, x/evm/types/errors.go, x/evm/types/gov_proposals.go, x/evm/types/message_submit_new_job_test.go, x/evm/types/turnstone_abi.go, x/paloma/keeper/keeper.go, x/scheduler/keeper/keeper.go, x/scheduler/keeper/wasm_handler.go, x/valset/client/cli/query_get_snapshot_by_id.go, x/valset/keeper/errors.go, x/valset/keeper/grpc_query_get_validator_jail_reason.go, x/valset/keeper/keep_alive.go, x/valset/keeper/keeper.go
- https://github.com/VolumeFi/paloma/issues/5
Fork some unpopular 3rdparty libraries to reduce risk of their removal
=> moved to forked whoops instead of the original one

.github/workflows/ci-test.yml
- https://github.com/VolumeFi/paloma/issues/9
Improving code quality
None
=> enable lints

app/upgrades.go
=> chore: update upgrade handler

app/app.go
=> create mem store keys

app/upgrades.go
=> Disable ICA host messages

app/app.go
This solves https://github.com/VolumeFi/paloma/issues/148
- https://github.com/VolumeFi/paloma/issues/148
=> Setting the Tx Encoded in the app

README.md
=> remove double https

README.md
Bringing the readme up to date for tomorrow's release in testnet.
=> Update readme for next release

README.md
Brings Readme instructions in master up to date for latest release
=> Bring readme instructions up to date

README.md, app/app.go, go.mod, go.sum
https://github.com/VolumeFi/paloma/issues/203
=> chore: upgrade cosmwasm to 0.40.1

.github/pull_request_template.md
The wording didn't make sense.  Hopefully now it does
=> Fixing odd wording in the PR template

README.md, RELEASE_NOTES.md
Release notes and readme update
=> Release notes and Readme update for new release

README.md, app/upgrades.go
=> Migration hack on public test net

README.md, go.mod, go.sum
- https://github.com/VolumeFi/paloma/issues/558
=> chore: update wasmvm

x/consensus/keeper/concensus_keeper.go
- https://github.com/VolumeFi/paloma/issues/780
- https://github.com/palomachain/paloma/issues/973
We often run into situations where response data from handling messages is lost as said messages leave the queue, leaving us to guess what happened. This change adds the response data to the Paloma log to be queried at a later stage in order to enrich the available information we have at our disposal.
=> feat: pigeon reponse data logging

x/valset/types/mocks/QueryServer.go
This should have been included in https://github.com/palomachain/paloma/pull/985 but was missed.  Pigeon needs this mock for its tests.
- N/A
=> Updating a mock needed by Pigeon

README.md, go.mod, go.sum
_A short paragraph about what exactly this PR solves and what is the problem._
=> Cosmwasm chain halt rollback (#999)

README.md, app/app.go
Update minimum required version of Pigeon and prepare README for `v1.10.0`
=> chore: increase minimum version of Pigeon

testutil/keeper/evm.go, testutil/keeper/treasury.go, x/evm/keeper/grpc_query_params_test.go, x/evm/keeper/keeper_integration_test.go, x/evm/keeper/scheduler_job.go, x/treasury/keeper/grpc_query_params_test.go
Test file fixes and testutil fixes for evm module
=> fix: evm module test file fixes in upgrading sdk v0.50

cmd/palomad/root.go
=> chore: fix wasm dir issue

README.md
https://github.com/VolumeFi/paloma/issues/1480
=> Update setup instructions for tumbler

x/gravity/keeper/pool.go, x/gravity/types/batch_test.go
=> chore: fix some function names

x/metrix/keeper/keeper.go
The existing annotations are problematic, fix the issue
=> chore: fix comment

x/consensus/types/mocks/QueryServer.go
Addresses a faulty mock that Pigeon needs to use.
=> fix: GetAllQueueNamesMock

util/keeper/id_generation_test.go, x/consensus/keeper/consensus/consensus.go, x/gravity/module.go
=> chore: fix some comments

app/app.go
- https://github.com/VolumeFi/paloma/issues/1661
Re-committing https://github.com/palomachain/paloma/pull/1146
=> fix: use default gov config

.github/workflows/ci-test.yml
Switch to GoTestSum for CI test runs.
=> ci: use gotestsum

README.md
Update README with release 1.15.1
=> chore: update README with v1.15.1

README.md
=> chore: update README to v1.15.5

README.md
_A short paragraph about what exactly this PR solves and what is the problem._
=> chore: Fix testnet node address in readme

README.md
Update README to point to v1.15.7
=> chore: update README to point to v1.15.7

README.md
=> chore: update README to v2.0.1

RELEASE_NOTES.md
Add release notes. I pushed the branch before the release notes, and now the branch is protected!
=> chore: add release notes to v2.0.1

README.md
=> chore: update readme to v2.1.0

README.md
=> chore: update README to v2.2.1

README.md
=> chore: update README to v2.2.2

README.md
=> chore: update README to v2.3.1

README.md
=> chore: update README to v2.3.2

x/scheduler/bindings/msg_plugin.go
=> fix (scheduler): inject expected wrapping in payload

.github/workflows/ci-test.yml, .golangci.yml, x/skyway/bindings/types/msg.go
- https://github.com/VolumeFi/paloma/issues/2616
Addresses incorrect snake case JSON bindings.
=> fix: snake case JSON bindings

util/libwasm/plugin.go
- https://github.com/VolumeFi/paloma/issues/2797
=> fix: WASM event swallowing
