palomachain/paloma

.gitattributes
proto/consensus/query.proto
x/consensus/keeper/grpc_query_consensus_reached.go
x/consensus/types/query.pb.go

- #83 
Given that the query endpoint for getting messages was made a while ago, it was made as a "placeholder". This PR creates new types to support this endpoint's requirements. It needs to send the message and validators that have signed it.

Query the consensus reached messages

---

x/consensus/keeper/concensus_keeper.go
x/consensus/keeper/concensus_keeper_test.go
x/consensus/keeper/concensus_queue.go
x/consensus/keeper/concensus_queue_test.go
x/consensus/keeper/errors.go
x/consensus/keeper/keeper.go

- https://github.com/palomachain/paloma/issues/105
Given that initial design used generics, it doesn't play well with the idea of using the attestation module. Given that attestation module is much more important than using generics, I am dropping them here in favour of easier API to use and making it easier for attestation module to come to life.

Redesign consensus queuer

---

x/consensus/keeper/concensus_keeper.go
x/consensus/keeper/concensus_keeper_test.go
x/consensus/keeper/concensus_queue.go
x/consensus/keeper/concensus_queue_test.go
x/consensus/keeper/grpc_query_consensus_reached.go
x/consensus/keeper/keeper.go
x/consensus/keeper/query_queued_messages_for_signing.go
x/consensus/types/consensus.go

- #105 
Want to bring a bit more security by ensuring that only custom type can be used for the queue name. This is more for hardening it in the future, as right now it doesn't really add much value.

Use custom type for consensus-queue-type

---

scripts/setup-chain-validator.sh

- None
Currently the script fails immediately when gsed is not installed. Fix this.

Fix setup-chain-validator failing if gsed is not installed.

---

README.md

https://github.com/palomachain/paloma/issues/143
Attempting to upgrade the palomad version resulted in corruption. Making a new testnet so people have something to connect to at least.

Make a new (uncorrupted) testnet based on an up-to-date palomad

---

x/consensus/keeper/concensus_keeper.go
x/evm/keeper/keeper.go
x/evm/keeper/keeper_integration_test.go

- #197 
Public keys are not really neccecary in the EVM world and to verify a signature, an address can be used. Thus using address for verifying EVM signatures.

Use address for ecrecover

---

cmd/palomad/main.go

- #209 
We have a memory leak.
zz
- `PPROF_LISTEN=localhost:7777 go run ./cmd/palomad start`
- `go tool pprof -inuse_space http://localhost:7777/debug/pprof/heap\?seconds\=10`

Add pprof for paloma

---

README.md

Fixes https://github.com/palomachain/paloma/issues/200
Main peer designator seems to have been required in earlier testnets, testing indicates we can do without it if the addrbook is initially seeded.

Use the addrbook.json as the single source of truth setting up testnets

---

README.md

https://github.com/palomachain/paloma/issues/247
There is no longer a command line accessible faucet. Staking command also needed to be tweaked, and mentioned as optional.

Exit readme to reflect current faucet and staking realities

---

app/modules.go

https://github.com/palomachain/paloma/issues/268
Normal default is 100, we would like more people to be able to be validators on the testnet.

Increase max_validators to 125

---

scripts/setup-chain-validator.sh
scripts/setup-volume-testnet.sh

https://github.com/palomachain/paloma/issues/267
This edit is done in DefaultGenesis now
Initialized a new testnet and:
```
> grep stake .paloma/config/genesis.json
> grep ugrain .paloma/config/genesis.json
"denom": "ugrain",
"base": "ugrain",
"denom": "ugrain",
"denom": "ugrain",
"mint_denom": "ugrain",
"bond_denom": "ugrain"
```

Remove s/stake/ugrain lines from setup scripts

---

README.md

Looks like we need to arrange the download of the addrbook AND the genesis AFTER unsafe-reset otherwise, the current flow won't work.
Just updating the ordering of the README instructions.

Move the addrbook and genesis get after unsafe-reset

---

x/valset/keeper/keeper.go
x/valset/keeper/keeper_test.go

- #356 
When building a snapshot, we need to add extra check to ensure that when folks have changed their external chain infos that we update the snapshot.

We should also trigger a snapshot build when external chain infos have changed

---

x/valset/keeper/keeper.go
x/valset/keeper/keeper_test.go

- https://github.com/palomachain/paloma/issues/373
Fixes incorrect way of calculating the validator's power percentage. Even though there was a test that was aimed to this trigger this, the numbers still worked though. The valset will trigger only when there was a change of 1% made. Given that `something big / something small` is always greater than `1%` (it's actually always going to be `>= 1`), then this always returned true as `something larger than 1 is always >= 1% (0.01)`.

Fix the way validator's power percentage was calculated

---

.goreleaser.yaml

Taken from: https://goreleaser.com/customization/archive/.
That way version is only written in the release URL which is generate by the github, so that we don't need to write it two times. Also it works with the latest release.

Remove version from filename when building the release

---

README.md

Just use the latest release in paloma's readme.

Use "latest" version for palomad download

---

.github/pull_request_template.md

There have been a few instances where I have thought or forgotten about code not being backwards compatible, which basically caused the testnet to halt. This is not super important for the testnet, but it's important for the mainnet, thus creating a reminder.

Add breaking change section to the PR template

---

app/app.go

- https://github.com/palomachain/paloma/issues/395
Cosmwasm was emitting an event, but paloma didn't know how to process it. Now it knows :).
This is a breaking change!
- [] If there are breaking changes, there is a supporting migration.

Wasm message handler

---

README.md

1. Update the README for update to palomad version 0.6.1
Updated README instructions for the community to install and update to the latest version of paloma 0.6.1
No testing completed. Instructions are simply to install
Removed the old genesis update instructions.

Update instructions for paloma 0.6.1 install

---

app/app.go

Upgrade name was supposed to be v0.6 while it has been v0.6.1
None

Fix for incorrect upgrade name

---

README.md
app/pigeon.go
cmd/palomad/main.go
go.mod

We want to stop folks from running paloma chain without them running pigeons. If paloma detects that pigeon is not running, it will kill itself thus stopping a _pigeonless_ validator from entering the valset.
Nope. It does not change anything in the state.

Pigeon healthcheck

---

x/valset/keeper/keep_alive.go
x/valset/keeper/keep_alive_test.go
x/valset/keeper/keeper.go

- #406 
We were iterating on list of all "good and honest" validators to see who is behaving badly, while we should have iterated over the list of all the validators
Yep!

Fix an issue jailing inactive validators

---

x/evm/keeper/keeper.go
x/evm/keeper/keeper_test.go
x/evm/types/expected_keepers.go
x/evm/types/mocks/ConsensusKeeper.go

- https://github.com/palomachain/paloma/issues/440
If the target chain is halted, then paloma will continue generating update valsets. Then queue of messages will start to fill up. Those messages then will need to leave from the queue to a target chain. Once they do then they do it in (somewhat) orderly style, thus valsets which are no longer true will still be deployed. This PR will clear the queue.
Yep!

Delete old valset updates

---

README.md

- Cleaning up the README again.
Readme had paloma testnet-7 to testnet-8 upgrade instructions still hanging.
Please check
None.

update README to remove paloma-testnet-7 and clean up again

---

README.md

Genesis for paloma-testnet-9
```json
{
"blockHashAtHeight": "0x872b621cdfd03de6c8d19e82ddfb524f9946242178903f8d6f2c540e7425ffb6",
"blockHeight": "15351127",
"chainID": "1",
"chainReferenceID": "eth-main",
"minOnChainBalance": "50000000000000000"
}
```
-------
https://eth-converter.com/

Update readme to match the new minimum for eth-main

---

x/evm/keeper/errors.go
x/evm/keeper/keeper.go
x/evm/keeper/keeper_test.go

- https://github.com/palomachain/paloma/issues/476
See https://github.com/palomachain/paloma/issues/476
Not a breaking change.

Incorrect argument types when calling a compass-evm logic call function

---

x/evm/keeper/keeper.go
x/evm/keeper/keeper_test.go
x/paloma/keeper/keeper_integration_test.go

Disable adding a new EVM chain if one with the chain id already exists
This is a breaking change.

Disable adding a new EVM chain if one with the chain id already exists

---

app/app.go
app/app_setup.go
testutil/keeper/paloma.go
x/paloma/keeper/keeper.go
x/paloma/keeper/keeper_integration_test.go
x/paloma/module.go
x/paloma/types/expected_keepers.go

Disable paloma if the version is different than what the government said should be
Not a breaking change.

Disable paloma if the version is different than what the government said should be

---

go.mod
go.sum

- https://github.com/palomachain/paloma/issues/517
Fixing the ignite's default migration version in the wasmd.

Upgrade wasmd to v0.29.0-rc2

---

x/consensus/keeper/attest.go
x/consensus/keeper/concensus_keeper.go
x/consensus/keeper/concensus_keeper_test.go
x/consensus/keeper/consensus/types.go
x/consensus/keeper/grpc_query_get_all_queue_names.go
x/evm/keeper/keeper.go

It's possible that `CheckAndProcessAttestedMessages` was causing the nondeterministic behaviour because it was iterating over the map.
Hopefully yes, but in a good way :)

Remove possible nondeterministic behaviour from the code

---

scripts/setup-volume-testnet.sh

There is no reason to change this and this setting deviates from anyone who initializes with the instructions in our readme, leading to confusion

remove keyring configuration

---

cmd/palomad/root.go

- Change default keyring backend from `test` to `os`
closes: #593

refactor: change default keyring backend

---

.mergify.yml
CHANGELOG.md

- Added CHANGELOG
- Note, there are no entries currently.
- Incoming changes from PRs (after this PR) must ensure to add relevant changelog entries under the `Unreleased` section.
- When a release is made, the release notes are populated from this changelog in the release branch.
- Created `release/v0.11.x` branch
- This is where changes from `master` will be backported to
- This release branch also contains the release notes
- Created backport label for `release/v0.11.x`
- Added mergify config for backporting and auto-merging
**NOTE** for repo/org admin:
- Ensure setup branch protection rules for release branches using `release/v*`.
- Ensure branch protection rules for `master` are up to date and correct
- Allow auto-merge (https://docs.github.com/en/repositories/configuring-branches-and- …

chore: release infra

---

Makefile

After building the code out of the v0.11.6, the palomad's version command's output is ostensibly malformed:
[alessio@fedora paloma]$ palomad version
HEAD-6a6c9280f76e0c5a510d80aebcfef4e94b7043c0
The git describe command used in the makefile needs both the --tags option and correct version number handling in order to print out correctly the version number inferred by a tagged commit.
Closes: #668

makefile: fix version handling

---

.github/dependabot.yml

- https://github.com/VolumeFi/paloma/issues/6
Cosmos SDK updates are backward incompatible, we want to update it manually

ignore cosmos in dependabot

---

app/app.go
cmd/palomad/root.go

Closes: #798 
Genesis commads are move to a seperate `genesis` sub command in cosmos-sdk v0.47.
This PR adds those genesis commands to the root cmd.
Also creating a new Genutil appmodule, as a genesis message validator is required.

add genesis commands

---

go.mod
go.sum

This reverts commit f2e6d757e296e89c09e4456286b49bb06a71524c.
This commit appears to be breaking paloma for new environments.  It is resulting in an inability to create new blocks, leaving the current height always at 0

Revert "Bump github.com/cometbft/cometbft from 0.37.0 to 0.37.1 (#809)"

---

.github/workflows/release.yml

* We need to release for tags like v1.0.0-beta1, which currently doesn't work.  This regex change should alow that

Allow releasing for tags with appended info

---

.goreleaser.yaml

The crux of this issue is that the version of glibc on the github machine that builds this vs that of those who run it may be different. We need to use this env variables build in the libraries instead of dynamically loading them on the host machine at runtime.

Fix GLIBC errors seen by some

---

README.md

The crux of this issue is that the version of glibc on the github machine that builds this vs that of those who run it may be different. Until this is fixed, we need to add instructions for people to build this on their own machine

Add in glibc gotcha and example to build from source

---

.goreleaser.yaml

This was done to try and get around glibc errors related to building on one machine and running on another.  This caused unexpected errors elsewhere and needs reverted to keep the master branch buildable.

Revert building with CGO disabled

---

app/upgrades.go

This will be backported for v1.1.0
When starting up, paloma is attempting to run upgrades meant for a previous version (v1.0.0).  This code should not be dynamic, as all upgrades are different.  We are now specifying the exact version this code is meant to run for.

Fixing broken v1.1.0 version

---

x/evm/keeper/keeper.go
x/evm/keeper/keeper_integration_test.go

Closes https://github.com/VolumeFi/paloma/issues/331
It was decided that we want to lengthen this to make quiet chains even cheaper

Lengthen the valset publish keep-warm time

---

x/valset/module.go

- https://github.com/VolumeFi/paloma/issues/254
This is meant as a stop-gap until we get to a better solution.  Pigeons are rejailed too quickly when unjailing.  We're slowing this process down slightly by not checking quite as often

Slow down rejailing slightly

---

cmd/palomad/root.go

This was done as part of a debugging effort, but seems useful to have in palomad.  Using these commands, we can easily manage snapshots ad-hoc

Adding commands for managing snapshots

---

.goreleaser.yaml

This has been deprecated, and as of the lastest release has been removed.  We have to make this change in order for the latest goreleaser to build
More info: https://goreleaser.com/deprecations/#archivesreplacements

Fixing goreleaser config for removed functionality

---

x/valset/module.go

This really just helps development.  We want to give both Paloma and Pigeon some time before we start worrying about jailing.  Now, we won't jail within the first 50 blocks of a new chain

Don't jail when starting up a new chain

---

x/consensus/keeper/attest.go
x/consensus/types/consensus.go

https://github.com/VolumeFi/paloma/issues/265
During the endblock handling, the entire message would get logged. The [stringer implementation](https://pkg.go.dev/golang.org/x/tools/cmd/stringer) for the underlaying message type was using the yaml package for a complete string marshalling, which resulted in a large amount of overhead. 
Logging the entire message in byte code not only take quite a long time due to marshalling, it's also largely irrelevant, as message information can easily be obtained from the queue.

🔧 fix: #265 remove yaml marshalling in endblock logging

---

x/valset/keeper/keep_alive.go
x/valset/module.go

Reverts palomachain/paloma#898
This appears to need some more work (and rolled back until the work is done).  It's causing errors when I run it in my local testnet, and most certainly will in mainnet
If I just kill a pigeon and let it reach the end of the TTL, palomad throws an error and breaks the chain.
```
Jul 05 18:50:31 m2 palomad[78744]: {"level":"error","module":"server","module":"consensus","height":217,"round":6,"err":"wrong Block.Header.AppHash.  Expected 437036D053C17E21AF21717F13B7479982589A423E68D757B8C996D6A2EEDC2F, got DBC723F7850C095868326648BFDE22D9C9AC26205190F5DBC48316DD84A00998","time":"2023-07-05T18:50:31Z","message":"prevote step: consensus deems this block invalid; prevoting nil"}
```
This error means we've created inconsistency between nodes.  The other nodes don't …

Revert "feat: #254 Jail pigeons after timeout"

---

util/libvalid/nil.go
x/paloma/keeper/keeper.go
x/paloma/types/expected_keepers.go
x/valset/keeper/grpc_query_get_alive_pigeons.go
x/valset/keeper/keep_alive.go
x/valset/keeper/keep_alive_test.go
x/valset/keeper/keeper.go
x/valset/keeper/keeper_test.go
x/valset/module.go

- https://github.com/VolumeFi/paloma/issues/254
This change adds a grace period for freshly unjailed validators,
preventing them from being jailed again immediately during the
next run of jailing.

#254 Add grace period for freshly unjailed validators

---

.gitignore

This is a directory commonly used for notes and local data.  Ignoring it in git

Ignoring a local directory used for notes

---

x/consensus/keeper/cleanup.go
x/consensus/keeper/cleanup_test.go
x/consensus/module.go

- https://github.com/VolumeFi/paloma/issues/461
We sometimes see messages stuck in our queues and need to address this problem.
Every 10 blocks, check the age of the messages currently in the queues. If a message is over 300 blocks (~30 minutes) old, we consider it stuck and delete it.  This prevents stuck messages from filling our queues.

Delete messages that are stuck in queues

---

x/consensus/keeper/attest.go
x/consensus/keeper/concensus_keeper.go
x/consensus/keeper/concensus_keeper_test.go
x/consensus/keeper/grpc_query_messages_in_queue.go
x/evm/keeper/keeper.go

- https://github.com/VolumeFi/paloma/issues/461
This will help with a couple things
1. If a single pigeon is acting up and leaving all of their messages in the queue, other pigeons will still get their messages.  A single pigeon's messages can no longer block other messges
2. If our queue is overfull, we can now see all messages currently in the queue, not just the first 200
Work done:
* Don't always require a limit on messages
* Adding an option to get all messages, not just N messages.  This is useful for times when we are going to filter the messages downstream.
* Move message response counts
* If we request a number of messages, we want that to be the number
returned, not the number before filtering
* Also fixing places that wanted all messages.  Now that we can return
all, let's just …

Better message limit handling

---

x/scheduler/client/cli/tx_create_job.go
x/scheduler/keeper/keeper.go
x/scheduler/keeper/msg_server_create_job.go
x/scheduler/types/job.go
x/scheduler/types/message_create_job.go

This output looks like it was put in a long time ago while debugging.  It's not using the log package, and it doesn't look like useful information to log.  Removing it to clean up our logs a bit.

Removing unnecessary output in logs using Println

---

x/gravity/abci.go
x/gravity/abci_test.go

- https://github.com/VolumeFi/paloma/issues/431
Until we finish adding the gravity features to Pigeon, we need to disable slashing in the gravity module.  We want this back, so it's just commented out for now to prevent buggy behavior in testnet.

Temporarily remove slashing functionality from Gravity

---

app/app.go

This release of Paloma requires features from the paired pigeon release in order to function properly.  Pigeons that are not at this version will be jailed.

Increase minimum pigeon version

---

app/upgrades.go
x/evm/keeper/keeper.go
x/evm/keeper/keeper_test.go
x/treasury/keeper/keeper_test.go
x/valset/keeper/keeper.go

- https://github.com/VolumeFi/paloma/issues/608
Adding the ability to force publish a valset to all chains.  Then taking this ability and applying it to when we come back from an upgrade.
We are very often just above 2/3 previous consensus when we come back from an upgrade, so we should publish the valset that has changed by that much, in case any validators have trouble right after the upgrade and go offline.
Adding some test cases adjacent to this new code, just to test the different paths
There is also a small logging fmt bug fix in here because it finally annoyed me too much.

Publish valset to all chains when returning from a software update

---

x/consensus/module.go

- https://github.com/VolumeFi/paloma/issues/630
We just increase our block speed drastically.  As such, we need to increase the amount of blocks to allow messages to remain stale. This is because we have more blocks per minute.
We also don't need to check quite as often for the same reason.

Increase the number of blocks to keep stale messages

---

proto/palomachain/paloma/evm/tx.proto
x/evm/client/cli/tx.go
x/evm/client/cli/tx_remove_smart_contract_deployment.go
x/evm/keeper/attest.go
x/evm/keeper/keeper.go
x/evm/keeper/keeper_integration_test.go
x/evm/keeper/msg_server_remove_smart_contract_deployment.go
x/evm/keeper/msg_server_remove_smart_contract_deployment_test.go
x/evm/keeper/smart_contract_deployment.go
x/evm/types/codec.go
x/evm/types/msg_remove_smart_contract_deployment_request.go
x/evm/types/tx.pb.go

- https://github.com/VolumeFi/paloma/issues/610
Paloma tracks smart contract deployments purely as a caching mechanism to prevent double-deploying too quickly.  We have an edge case where a deployment fails to go through for too long, it will get stuck.  Paloma will think it's deploying, but the message was long since deleted.
Now, we have a way of deleting this stuck deployment.  This is effectively the same as clearing the cache flag, and the chain will trigger a fresh deployment on the next block.

Add cli command to delete any stuck smart contract deployments

---

README.md

This needs done after every release.  We released yesterday.
Even though we're about to have a 1.7.1 release, we want the readme to remain at 1.7.0.
1.7.1 will work for cli commands, but it will not work for validators because of the version upgrade checking.

Update readme in master for v1.7.0 release

---

x/evm/keeper/msg_assigner.go
x/evm/keeper/msg_assigner_test.go

This was already tested and merged into master.  We want it in the current release

fix: validator selection with  multiple MEV chains configured

---

app/app.go

Upgrading the minimum required pigeon version to `v1.6.0`

chore: upgrade Pigeon dependency to v1.6.0

---

app/app.go
testutil/keeper/valset.go
x/gravity/keeper/keeper.go
x/paloma/keeper/keeper_integration_test.go
x/valset/keeper/keep_alive_test.go
x/valset/keeper/keeper.go
x/valset/keeper/keeper_integration_test.go
x/valset/keeper/setup_test.go

- https://github.com/VolumeFi/paloma/issues/708
The only security measurement in place during jailing so far was a check to see that Paloma would not run with less than 1 validator. 
This change adds a new safeguard, making sure that a validator will not be jailed if they're holding 25% or more of the entire network stake.

feat: 🔧 prevent jailing high stake validators

---

x/gravity/types/batch.go
x/gravity/types/batch_test.go

- https://github.com/VolumeFi/paloma/issues/517
This was put off because I didn't fully understand how Compass hashed batches before comparing signatures.  Now, I've come back to this and fixed it to sign exactly like Compass expects.
The test used here is using a real example, to ensure it works exactly as expected.

Fix signing of gravity batches

---

proto/palomachain/paloma/paloma/tx.proto
x/paloma/keeper/msg_server.go
x/paloma/types/codec.go
x/paloma/types/msg_add_status_update.go
x/paloma/types/tx.pb.go

- https://github.com/VolumeFi/paloma/issues/780
There are some cases in which we're still lacking proper visibility, especially during operations running on individual Pigeons that do not return an error in order to enable retries, i.e. during message processing without consensus.
This change adds a new gRPC endpoint to Paloma that will do nothing else aside from adding the given string in a log message for us to intercept. The behaviour is guarded behind a feature flag in order to disable it by default and prevent malicious flooding of nonsense messages.

Add pigeon status updates to Paloma

---

go.mod
go.sum

We believe this to be the culprit of our chain halt in mainnet.  Rather than trying to roll forward with fixes, we have decided it's safer to roll back.  This reverts https://github.com/palomachain/paloma/pull/971/files
- None needed, as this is a rollback

Rollback wasmvm version

---

x/paloma/types/codec.go

It's possible the errors we see in https://github.com/palomachain/paloma/issues/1006 are stemming from the message not getting registered against the interface registry, although I'm still unsure why it works some times and not others.
Testing this in private test net is currently very difficult, with the amount of `account sequence mismatch` leading to chain halts.

tryfix: paloma status update tx parsing failure

---

x/valset/keeper/keep_alive.go
x/valset/keeper/keeper_test.go

- https://github.com/VolumeFi/paloma/issues/856
Increasing the TTL to approx. 50 minutes. Pigeons will start calling in 15 minutes before. This should give enough leeway to allow us to bring back locking and avoid the `account sequence mismatch` error.

fix: ease keep-alive duration

---

x/consensus/keeper/concensus_keeper.go
x/consensus/keeper/concensus_keeper_test.go
x/consensus/keeper/keeper_setup_test.go

- https://github.com/VolumeFi/paloma/issues/855
This change adds an additional filter when Pigeons ask for any messages for relaying. It will hold off on returning any SLC messages on target chains that have pending valset updates.
This takes care of two race conditions:
- ValsetUpdate & SLC deployed by same Pigeon: replaying of both messages happens VERY quickly in succession -> high risk of `Incorrect Checkpoint` error
- ValsetUpdate & SLC deployed by two different Pigeons: even higher risk, as the SLC might get relayed BEFORE the valset update
With this change, SLC messages will never be given out to Pigeons as long as a previous valset update is still outstanding, meaning there is no way it would get delivered before the valset update or in too close a succession.

feat: hold SLC until JIT valset update is processed

---

x/evm/keeper/msg_assigner.go
x/evm/keeper/msg_assigner_test.go

- https://github.com/VolumeFi/paloma/issues/944
There's a hen & egg situation in case we're currently onboarding a new chain on Paloma, as the chain status is not yet active, Validators without full support for the new chain will still be within the active validator set.
This change adds target chain awareness when filtering for viable message relayers, ensuring that validators with missing chain support for the required target chain are no longer considered.

fix: assigning msgs to validators w/o chain support

---

x/evm/keeper/msg_assigner_test.go
x/gravity/keeper/msg_server.go

The current logging format is pretty useless and doesn't allow to query for transactions via event predicates. This should help.

fix: gravity message logging format

---

.github/workflows/release.yml
.golangci.yml
Dockerfile
go.mod
go.sum

We've pulled in some features from Go 1.21 during the pigeon operator key work, but it's a good idea to keep up with the latest patches in any case.

chore!: upgrade go to 1.21

---

x/scheduler/keeper/msg_server_execute_job.go

This panic crept in with the changes made to support Pigeon keys and went through unnoticed until today. This fix addresses the problem by calling the proper parsing function. There is unfortunately ZERO testing in place for CLI commands still. Hopefully something we can tackle in the future so things like this don't happen again.

fix: prevent panic in job execution command

---

x/paloma/ante.go

- https://github.com/VolumeFi/paloma/issues/1014
- https://github.com/VolumeFi/paloma/issues/1013
After more investigation, it's become apparent that there are transactions which are being rejected in the CometBFT mempool, I don't think they ever reach the app mempool. 
The reason for the rejection is the account sequence mismatch. Theoretically, this should be verified when submitting a transaction.
Looking at the code, there is a precondition in our ante handler for signature verification that's being skipped if we're running `CheckTX` - so it's possible for a transaction that would actually fail to still be included in the mempool, as it looks like the check is only run once the TX is actually executed.
Tested this in public test net against a dev build and had promising results, …

fix: ante handler skip condition

---

go.mod
go.sum

- https://github.com/VolumeFi/paloma/issues/1254
- https://github.com/Agoric/agoric-sdk/issues/8783
Also see: https://github.com/Agoric/agoric-sdk/commit/bc4a284e7346369f64757be20543045df52e8c3b

chore: refresh ledger depdendencies

---

x/consensus/module.go
x/evm/module.go
x/metrix/module.go
x/paloma/module.go
x/scheduler/module.go
x/treasury/module.go
x/valset/module.go

- https://github.com/palomachain/paloma/issues/1083
- https://github.com/VolumeFi/paloma/issues/1257
All custom modules have at least some HTTP API endpoints configured, but none of them were enabled. This change makes sure all modules register their endpoints accordingly. Make sure to set `api.enable` to `true` in `~/.paloma/config/app.toml` by default the API is disabled.

feat: enable gRPC HTTP gateway

---

x/consensus/keeper/concensus_keeper.go

- https://github.com/VolumeFi/paloma/issues/1409
Some messages might still fail to be handled at all, meaning the message will not even enter the attestation phase. In this case, we do not want to punish validators - otherwise we'd jail the entire network.
Merging this into `devel`, which was taken from `release/v1.12.2`. That will be my working branch for a `v1.12.3` release in case `master` remains blocked due to the Cosmos upgrade.

hotfix: prevent punishing missing attestants for unhandled msg

---

util/libcons/consensus.go
x/consensus/keeper/cleanup_test.go
x/consensus/keeper/concensus_keeper.go
x/consensus/keeper/concensus_keeper_test.go

- https://github.com/VolumeFi/paloma/issues/1425
This change adds two safe guards to prevent a mass jailing in case of a faulty message:
a) messages that do not build consensus because neither `errorData` nor `publicAccessData` has been added, meaning the message was never handled in the first place. Nobody should be punished for not attesting what's not attestable.
b) messages that less than 10% of the network attest are treated as indications of faulty message responses which cannot be attested to even when tried. Nobody will be punished for missing attestation on such a message.

fix: prevent TPK when not attesting faulty msg

---

cmd/palomad/commands.go
go.mod

- Increase Go version to `1.22.2`
- Fix libwasm version during application startup

chore: increase go version to 1.22.2 and fix libwasm version

---

cmd/palomad/commands.go
cmd/palomad/testnet.go
go.mod

Adds command to setup a testnet:
```sh
palomad testnet init-files --chain-id=testing --output-dir=./testnet --v=4 --keyring-backend=test --minimum-gas-prices=0.000001ugrain --staking-denom=ugrain --commit-timeout=900ms --single-host --starting-ip-address=""
```
Disclaimer: 
copied from wasmd which came from cosmos-sdk/simapp with some modifications

Add testnet command

---

.github/workflows/release.yml
Makefile

The leading v prefix in the app version is used both in CI builds
as well as the test net setup. Pigeon also uses it. It makes
no sense to remove it from manual builds, especially as it can
lead to differences in state.

fix: include v prefix in app version

---

README.md
app/app.go

Bump Pigeon to `v1.11.2` and update README

chore: bump Pigeon version

---

util/keeper/errors.go
x/consensus/keeper/concensus_keeper.go
x/consensus/keeper/consensus/batch.go
x/consensus/keeper/consensus/batch_test.go
x/consensus/keeper/consensus/consensus.go
x/consensus/keeper/consensus/errors.go
x/evm/keeper/keeper.go
x/evm/keeper/scheduler_job.go
x/valset/keeper/keeper.go

- https://github.com/VolumeFi/paloma/issues/1591
Clanup possible runtime panics picked up by CodeQL analysis.
CodeQL still reports 6 panics in BeginBlock or EndBlock - [here](https://github.com/palomachain/paloma/security/code-scanning?query=%22Panic+in+BeginBlock%22+is%3Aopen+pr%3A1172+) - but I think we want to keep those. They all come from 2 points in the code:
- [CheckChainVersion](https://github.com/palomachain/paloma/blob/546372207dd2eb535590697c49264ab1d1e1b152/x/paloma/module.go#L174-L174) to make sure we're running the intended palomad version
- [Closing attestation iterators](https://github.com/palomachain/paloma/blob/546372207dd2eb535590697c49264ab1d1e1b152/x/gravity/keeper/attestation.go#L314-L314) - since we can't close the iterator, it is my understanding we won't be able …

Fix panics picked up by Codeql

---

x/gravity/keeper/genesis.go

- https://github.com/VolumeFi/paloma/issues/1654
The `GravityNonces` changed to an array, so now we have to call `SetLastSlashedBatchBlock` manually if it's empty.

fix: gravity genesis export

---

x/valset/module.go

- https://github.com/VolumeFi/paloma/issues/1676
Only log other errors, as `ErrNotFound` is expected until we save some scheduled pigeon requirements.

Silence scheduled requirements ErrNotFound log messages

---

x/evm/keeper/attest_validator_balances.go
x/evm/keeper/attest_validator_balances_test.go
x/evm/types/jail_reason.go

- https://github.com/VolumeFi/paloma/issues/1037
If validators have invalid (or missing) balances, we jail them. Alternatively we could leave them out of the relayer pool, but this makes it more visible when something has failed.
For this mechanism to work properly, we need https://github.com/palomachain/pigeon/pull/399 to be merged as well.

chore: jail validators with invalid balances

---

app/app.go
tests/integration/evm/keeper/keeper_integration_test.go
tests/integration/evm/keeper/test_helpers_test.go
util/eventbus/bus.go
util/eventbus/bus_test.go
x/consensus/keeper/concensus_keeper.go
x/evm/keeper/keeper.go
x/evm/keeper/smart_contract_deployment.go
x/evm/types/types.go
x/gravity/keeper/batch.go
x/gravity/keeper/grpc_query.go
x/gravity/keeper/grpc_query_test.go
x/gravity/keeper/keeper.go
x/gravity/keeper/test_common.go
x/gravity/types/expected_keepers.go

- https://github.com/VolumeFi/paloma/issues/1464
This change adds a new constraint when handing out gravity batches to be relayed. They will now be withheld while valset updates are pending on the target chain, just like with SLC. I had to cut some corners to get this out sooner rather than later, but I also added a more decentralised event bus system for decoupling systems. It's currently very bare bone and as singleton hard to test, but if it grows, we can refactor into something more injectible.

fix: withold gravity batches until valset update

---

x/consensus/keeper/concensus_keeper.go

- Closes https://github.com/VolumeFi/paloma/issues/1740
ReferenceBlockAttestation messages currently do not need an assignee, however they are still queried for messages to relay, leading to unpack error messages in palomad logs.
By first checking for publicAccessData, ReferenceBlockAttestation messages are filtered before we try to unpack them as TurnstoneMsg and avoid the errors.

fix: unpack errors on ReferenceBlockAttestation

---

x/consensus/keeper/concensus_keeper.go
x/consensus/keeper/concensus_keeper_test.go
x/consensus/keeper/filters/assigned_to_filter.go
x/consensus/keeper/filters/assigned_to_filter_test.go
x/consensus/keeper/filters/is_oldest_per_sender_filter.go
x/consensus/keeper/filters/is_oldest_per_sender_filter_test.go
x/consensus/keeper/filters/pending_valset_filter.go
x/consensus/keeper/filters/pending_valset_filter_test.go
x/consensus/keeper/filters/unprocessed_filter.go
x/consensus/keeper/filters/unprocessed_filter_test.go

- https://github.com/VolumeFi/paloma/issues/1760
This change prevents multiple messages from the same
sender to be relayed in parallel, even by different
relayers. This is a preliminary security step for
pigeon feed to prevent exploitable race conditions.
There's also some house keeping and tidying around
the filtering logic.

feat: Prevent parallel delivery of same sender msgs

---

x/evm/keeper/attest_submit_logic_call.go
x/evm/keeper/attest_submit_logic_call_test.go
x/evm/keeper/smart_contract_deployment.go
x/skyway/keeper/grpc_query.go
x/skyway/types/expected_keepers.go

- https://github.com/VolumeFi/paloma/issues/1050
- https://github.com/VolumeFi/paloma/issues/1802
This change will make sure that ERC20 transfers are being retried continuously instead of stopping after 2 retries to try and attempt to prevent a deadlock. There might still be a need for a manual unlock down the road.
Additionally, we now make sure to stop processing skyway messages while we have an ongoing contract deployment, to avoid a desync of the nonces on the old and new compass.

feat: remove retry limit from erc20 transfers

---

go.mod
go.sum

- https://github.com/VolumeFi/paloma/issues/1862
This raises IAVL to the latest `1.1.x` dependency.

chore: upgrade IAVL to 1.1.4

---

x/consensus/keeper/concensus_keeper.go
x/consensus/keeper/consensus/consensus.go
x/evm/keeper/attest.go
x/evm/types/eth_txable.go
x/evm/types/turnstone_abi.go

- Closes https://github.com/VolumeFi/paloma/issues/1875
UpdateValset and SubmitLogicCall messages would fail to attest if:
* Some pigeons sign the message in the queue and a pigeon picks it up
* While this pigeon is relaying the message, some more pigeons sign it
* When we try to attest it, the SignData in paloma doesn't match the SignData of the original message, since more pigeons signed it since!
To fix it, we iterate through the message SignData and remove the last signature until we get a match, or there are no more signatures.

fix: message attestation with wrong sign data

---

x/paloma/keeper/keeper.go

- https://github.com/VolumeFi/paloma/issues/1865
We need to setup the license first, and only then do the feegrant, otherwise the account will already exist and fail the check.

fix: feegrant order in light node licenses

---

x/evm/keeper/msg_assigner.go

- Closes https://github.com/VolumeFi/paloma/issues/1929
We need to ensure validators are ordered even if they have the same score, otherwise the result might not be deterministic.

fix: sort validators with same score by address

---

Makefile

This allow us to customize the build, for instance to build with muslc instead of glibc.

chore: add optional BUILD_TAGS to Makefile

---

x/skyway/keeper/grpc_query.go

fix: Skyway query should filter estimates by chain ID

---

x/evm/keeper/attest_test.go
x/evm/keeper/attest_upload_smart_contract.go

- https://github.com/VolumeFi/paloma/issues/1891
Even if we don't want to move test tokens, since we have them set, paloma will still try to move them. This will fail since (new) pigeon won't be compatible with (old) compass, so we need to disable this functionality before compass 2.0 is deployed and re-enable it again afterwards.

chore: disable token relink before compass 2.0

---

x/evm/keeper/keeper.go
x/evm/keeper/keeper_test.go

- Closes https://github.com/VolumeFi/paloma/issues/1042
Before issuing a jit valset update, check the queue for existing valset updates with the same ID.

fix: jit valset updates in SLCs

---

x/evm/keeper/attest_test.go
x/evm/keeper/attest_upload_smart_contract.go
x/evm/types/expected_keepers.go
x/evm/types/mocks/SkywayKeeper.go
x/skyway/keeper/cosmos-originated.go

- Closes https://github.com/VolumeFi/paloma/issues/1953
When some chain has ERC20 tokens deployed, compass upgrades would be stuck on chains that do not have tokens. Now we only query deployed tokens for the specific chain currently being iterated.
NOTE: After deploying this change, we have to manually remove any stuck compass upgrade. It should redeploy automatically afterwards.

fix: compass attestation with ERC20 tokens

---

README.md
x/evm/keeper/attest_test.go
x/evm/keeper/attest_upload_smart_contract.go
x/evm/types/expected_keepers.go
x/evm/types/mocks/SkywayKeeper.go
x/skyway/keeper/cosmos-originated.go

Merge master back to dev16 branch.

chore: merge dev16 master

---

x/scheduler/keeper/wasm_handler.go

SLCs generated from CosmWasm contracts were setting the `ContractAddress` field, but not the `SenderAddress` field. This is an issue for pigeon feed. We now set both fields on these calls.

fix: set senderAddress in SLCs from CW

---

x/evm/keeper/keeper.go
x/evm/keeper/keeper_test.go
x/evm/module.go

- Closes https://github.com/VolumeFi/paloma/issues/1040
If a JIT ValsetUpdate fails, it can lead to SLC messages being stuck. In order to overcome this, we set a watcher on the end blocker to insert new ValsetUpdates when needed if there is an SLC message in the queue (or UploadUserSmartContract message).

fix: prevent stuck SLCs waiting for valset

---

x/paloma/keeper/keeper.go
x/paloma/keeper/keeper_test.go

- https://github.com/VolumeFi/paloma/issues/2105
Fix the units on the node sale amounts.

fix: set light node sale amount in GRAIN

---

util/libcons/consensus.go
x/consensus/keeper/estimate_test.go
x/skyway/abci_test.go

- https://github.com/VolumeFi/paloma/issues/2089
This change addresses the inflated estimate that used to include a `1.2` modifier applied to the limit in as a security margin.

feat: adapt gas estimation to reduce 120% safety buffer

---

x/skyway/keeper/attestation.go
x/skyway/keeper/keeper.go

- https://github.com/VolumeFi/paloma/issues/2159
When a claim is set to observed, update all validator nonces if they have a lower last observed nonce.
NOTE: This only takes effect when a claim is successfully attested to. The validators currently stuck will remain on their current nonces until a claim is processed. To get them unstuck, we need https://github.com/VolumeFi/paloma/issues/2160

chore: update skyway validator nonces

---

app/app.go
app/upgrades.go

- https://github.com/VolumeFi/paloma/issues/2163
Add the authz module to paloma, so we can grant authorizations to delegate and claim rewards.
NOTE: this adds a migration assuming the next release is going to be 2.2.1

feat: add authz module

---

x/skyway/keeper/attestation.go
x/skyway/keeper/grpc_query_test.go

- https://github.com/VolumeFi/paloma/issues/2160
If we ever reset the latest skyway nonce ahead of any observed claim, we don't need nor want pigeons trying to attest to them. So, we can filter claims that are behind the latest attested claim.
This should prevent pigeons from getting stuck trying to get old claims if their RPC fails, and we need to reset the nonce ahead of observed claims.

chore: ignore claims behind last observed nonce

---

x/skyway/abci.go
x/skyway/keeper/attestation.go
x/skyway/keeper/keeper.go

- https://github.com/VolumeFi/paloma/issues/2160
The way it was before, we would need a claim to be observed so validators would be updated. By doing it in the endblocker, we validators are always up-to-date.
This should prevent a situation where the last claim is 19, the last observed nonce is 18, but validators are stuck on nonce 17. They would receive a list of block events with the block of nonce 19 (latest unobserved) but would be unable to claim it, since skyway would expect them to submit a claim for nonce 18 instead.

chore: update validator nonces in endblocker

---

tests/integration/metrix/keeper/keeper_intergration_test.go
x/evm/keeper/msg_assigner.go
x/evm/keeper/msg_assigner_test.go
x/metrix/keeper/keeper.go

- Closes https://github.com/VolumeFi/paloma/issues/2193
At the moment we always pick the same validator to relay messages. We need to improve this mechanism to pick different validators, especially if the one selected is failing to relay messages. With this PR:
* We will pick randomly from the top 5 validators.
* On every failed message delivery, the success rate of a validator drops to the base score of 0.5 if it's above 0.5.

feat: improve relayer picking

---

app/app.go
x/scheduler/bindings/msg_plugin.go
x/scheduler/bindings/query_plugin.go
x/scheduler/bindings/types/msg.go
x/scheduler/bindings/types/query.go
x/scheduler/bindings/types/types.go
x/scheduler/bindings/wasm.go
x/scheduler/client/cli/tx_create_job.go
x/scheduler/types/message_create_job.go
x/tokenfactory/bindings/msg_plugin.go
x/tokenfactory/bindings/queries.go
x/tokenfactory/bindings/query_plugin.go
x/tokenfactory/bindings/types/msg.go
x/tokenfactory/bindings/types/query.go
x/tokenfactory/bindings/types/types.go
x/tokenfactory/bindings/wasm.go

- https://github.com/VolumeFi/paloma/issues/2459
This change adds experimental bindings for the token factory, as well as a limited scope of the scheduler module, allowing jobs to be queried and created from smart contracts. 
Bindings are untested and should be treated as experimental.

feat: experimental wasm bindings for token factory & scheduler

---

app/app.go
x/paloma/ante.go
x/paloma/ante_test.go

- https://github.com/VolumeFi/paloma/issues/2466
This change introduces as custom `TxFeeChecker` implementation, which simply returns an empty fee for every transaction, as well as a constant priority.
Merging this change will lead to an equal transaction prioritization across Paloma, without the option to incentivize validators to include a transaction in an earlier block.

feat: add fee skipping

---

cmd/palomad/commands.go

- https://github.com/VolumeFi/paloma/issues/1162
Enforces optimistic execution across all nodes. PTN tests are looking good, but our mileage may vary depending on cross chain chatter.

chore: enable optimistic execution

---

x/scheduler/bindings/legacy.go

- https://github.com/VolumeFi/paloma/issues/2497
Removes an unused field from the scheduler module legacy bindings. Additional fields are discarded, so backwards compatibility is not broken here.

chore: remove legacy binding field

---

app/app.go
util/libwasm/plugin.go
util/libwasm/plugin_test.go
x/scheduler/bindings/msg_plugin.go
x/skyway/bindings/msg_plugin.go
x/tokenfactory/bindings/msg_plugin.go

- https://github.com/VolumeFi/paloma/issues/2531
This change addresses a bug in the way custom `wasm` messages are parsed and routed to target modules.

fix: wasm binding integrations

---

.github/workflows/ci-test.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
.golangci.yml
Dockerfile
Makefile
README.md
go.mod

- https://github.com/VolumeFi/paloma/issues/2540
- Lock the CI runner versions
- Upgrade to the latest released version of Go

ci: increase Go version

---

x/skyway/keeper/msg_server.go
x/skyway/types/errors.go

- https://github.com/VolumeFi/paloma/issues/2641
This change adds a check that prevents binding a `denom` to an ERC20 address that is already bound.
> [!important]
> This will prevent updating your ERC20 addresses against your own denoms even, but it could theoretically be implemented at a later stage.
> [!warning]
> The underlaying gravity bridge code was not written with more than one remote chain in mind. Therefore, after this change, it will not be possible to use the same Ethereum address for a denom on more than one remote chain, so deterministic addresses cannot be used anymore.

fix: prevent mapping multiple denoms to same ERC20

---

util/libwasm/plugin.go
util/libwasm/plugin_test.go
x/evm/keeper/smart_contract_deployment.go

- https://github.com/VolumeFi/paloma/issues/2725
This change ensures that any events emitted by Paloma in the context of a CW message call will be correctly attached to the transaction. For some reason, that is not the case by default.

chore: emit event on consensus message creation

---

app/mempool/priority_nonce.go
x/skyway/abci.go

fix: ensure deterministic tx order in mempool
